package com.icthh.xm.uaa.config.tenant;

import com.icthh.xm.commons.logging.util.MDCUtil;
import com.icthh.xm.uaa.config.Constants;
import lombok.experimental.UtilityClass;

@UtilityClass
@SuppressWarnings("squid:S1118") // private constructor generated by lombok
public class TenantContext {

    private static ThreadLocal<TenantInfo> current = ThreadLocal
        .withInitial(() -> new TenantInfo(Constants.DEFAULT_TENANT, "", "", "", "", "", ""));

    public static void setCurrent(TenantInfo info) {
        current.set(info);
        MDCUtil.putRid(MDCUtil.generateRid() + ":" + info.getUserLogin() + ":" + info.getTenant());
    }

    public static void setCurrent(String tenant) {
        setCurrent(new TenantInfo(tenant, "", "", "","", "", ""));
    }

    public static void setDefault() {
        setCurrent(new TenantInfo(Constants.DEFAULT_TENANT, "", "", "", "", "", ""));
    }

    public static TenantInfo getCurrent() {
        return current.get();
    }

    public static void clear() {
        current.remove();
        MDCUtil.clear();
    }
}
